In [1]:
import requests
from retry import retry
from tqdm import tqdm
import numpy as np
import torch

In [2]:
import os
from sys import platform

if platform == 'win32':
    os.chdir('/'.join(os.getcwd().split('\\')[:-2]))
else:
    os.chdir('/'.join(os.getcwd().split('/')[:-2]))
from src import *

In [10]:
test,_ = get_raw_text_cora(use_text=False)

In [12]:
test.x

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [3]:
LM_emb_path = './prt_lm/cora/microsoft/deberta-base-gpt.emb'
features = np.array(
                np.memmap(LM_emb_path, mode='r',
                          dtype=np.float16,
                          shape=(2708, 768)))

In [4]:
features.shape

(2708, 768)

In [5]:
#embed = np.array(output)
np.savetxt('TAPE_embed_Cora_deb.txt',features)

In [27]:
features = np.loadtxt('LM_embed_Cora_deb.txt')
features.shape

(2708, 768)

In [18]:
import pandas as pd

In [21]:
import matplotlib.pyplot as plt

In [24]:
np.mean(pd.DataFrame(em).corr())

0.0002822086699942494

In [7]:
LM_pred_path = './prt_lm/cora/microsoft/deberta-base-raw-text.pred'
preds = np.array(
                np.memmap(LM_pred_path, mode='r',
                          dtype=np.float16,
                          shape=(2708, 7)))

In [11]:
import torch
import itertools
from torch_geometric.datasets import Planetoid, Actor
from torch_geometric.transforms import NormalizeFeatures
from tqdm import tqdm

In [13]:
data = Planetoid(root='data/Planetoid', name='Cora', transform=NormalizeFeatures())[0]

In [16]:
data['y']

tensor([3, 4, 4,  ..., 3, 3, 3])

In [23]:
np.savetxt('LM_pred_Cora.txt',preds)

In [29]:
test = np.concatenate([features,preds],axis=1)

In [30]:
test.shape

(2708, 775)

In [33]:
full_pred = np.argmax(preds,axis=1)

In [34]:
full_pred

array([2, 5, 4, ..., 1, 0, 2], dtype=int64)

In [41]:
np.where(full_pred==data['y'].numpy())[0].size

396