In [1]:
import pandas as pd

In [2]:
from ogb.nodeproppred import PygNodePropPredDataset

In [3]:
dataset = PygNodePropPredDataset(name = 'ogbn-arxiv') 

Downloaded 0.00 GB:   1%|          | 1/81 [00:19<25:30, 19.13s/it]

KeyboardInterrupt



In [2]:
import os
from sys import platform

if platform == 'win32':
    os.chdir('/'.join(os.getcwd().split('\\')[:-2]))
else:
    os.chdir('/'.join(os.getcwd().split('/')[:-2]))
from src import *

In [3]:
def run(cfg):
    seeds = [cfg.seed] if cfg.seed is not None else range(1)
    all_acc = []
    for seed in seeds:
        cfg.seed = seed
        trainer = LMTrainer(cfg)
        trainer.train()
        acc = trainer.eval_and_save()
        all_acc.append(acc)

    if len(all_acc) > 1:
        df = pd.DataFrame(all_acc)
        for k, v in df.items():
            print(f"{k}: {v.mean():.4f} ± {v.std():.4f}")

In [4]:
cfg

CfgNode({'dataset': 'cora', 'device': 0, 'seed': None, 'lm': CfgNode({'model': CfgNode({'name': 'microsoft/deberta-base', 'feat_shrink': ''}), 'train': CfgNode({'batch_size': 9, 'grad_acc_steps': 1, 'lr': 2e-05, 'epochs': 4, 'warmup_epochs': 0.6, 'eval_patience': 50000, 'weight_decay': 0.0, 'dropout': 0.3, 'att_dropout': 0.1, 'cla_dropout': 0.4, 'use_gpt': False})}), 'text_type': 'raw'})

In [45]:
cfg = update_cfg(cfg, 'cora', 'gpt')

In [46]:
cfg

CfgNode({'dataset': 'cora', 'device': 0, 'seed': 0, 'lm': CfgNode({'model': CfgNode({'name': 'microsoft/deberta-base', 'feat_shrink': ''}), 'train': CfgNode({'batch_size': 9, 'grad_acc_steps': 1, 'lr': 2e-05, 'epochs': 4, 'warmup_epochs': 0.6, 'eval_patience': 50000, 'weight_decay': 0.0, 'dropout': 0.3, 'att_dropout': 0.1, 'cla_dropout': 0.4, 'use_gpt': False})}), 'text_type': 'gpt'})

In [ ]:
run(cfg)

In [6]:
run(cfg)

preproc
tokenizer
<class 'torch.utils.data.dataset.Subset'>


Some weights of the model checkpoint at microsoft/deberta-base were not used when initializing DebertaModel: ['lm_predictions.lm_head.dense.bias', 'lm_predictions.lm_head.bias', 'lm_predictions.lm_head.LayerNorm.weight', 'lm_predictions.lm_head.LayerNorm.bias', 'lm_predictions.lm_head.dense.weight']
- This IS expected if you are initializing DebertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DebertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).



Number of parameters: 138607111
Start running train at 11-13 13:40:36


D:\anaconda\envs\stare\lib\site-packages\transformers\optimization.py:391: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


LM saved to prt_lm/cora/microsoft/deberta-base-seed0.ckpt
Finished running train at 11-13 15:19:55, running time = 1.66h.
Start running eval_and_save at 11-13 15:19:55


[LM] TrainAcc: 0.9526, ValAcc: 0.8026, TestAcc: 0.7970

Finished running eval_and_save at 11-13 15:29:20, running time = 9.41min.


C:\Users\Nathan Paull\github\personal\gnn_project\src\lm_trainer.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  "y_true": torch.tensor(labels).view(-1, 1),


# GPT Text

In [5]:
cfg = update_cfg(cfg, 'cora', 'gpt')

In [6]:
cfg

CfgNode({'dataset': 'cora', 'device': 0, 'seed': None, 'lm': CfgNode({'model': CfgNode({'name': 'microsoft/deberta-base', 'feat_shrink': ''}), 'train': CfgNode({'batch_size': 9, 'grad_acc_steps': 1, 'lr': 2e-05, 'epochs': 4, 'warmup_epochs': 0.6, 'eval_patience': 50000, 'weight_decay': 0.0, 'dropout': 0.3, 'att_dropout': 0.1, 'cla_dropout': 0.4, 'use_gpt': False})}), 'text_type': 'gpt'})

In [7]:
run(cfg)

new load
<class 'torch.utils.data.dataset.Subset'>


Some weights of the model checkpoint at microsoft/deberta-base were not used when initializing DebertaModel: ['lm_predictions.lm_head.dense.bias', 'lm_predictions.lm_head.dense.weight', 'lm_predictions.lm_head.bias', 'lm_predictions.lm_head.LayerNorm.weight', 'lm_predictions.lm_head.LayerNorm.bias']
- This IS expected if you are initializing DebertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DebertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).



Number of parameters: 138607111
Start running train at 11-13 16:34:35


D:\anaconda\envs\stare\lib\site-packages\transformers\optimization.py:391: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


LM saved to prt_lm/cora/microsoft/deberta-base-seed0.ckpt
Finished running train at 11-13 16:51:52, running time = 17.28min.
Start running eval_and_save at 11-13 16:51:52


[LM] TrainAcc: 0.9083, ValAcc: 0.7823, TestAcc: 0.7970

Finished running eval_and_save at 11-13 16:57:16, running time = 5.40min.


C:\Users\Nathan Paull\github\personal\gnn_project\src\lm_trainer.py:278: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  "y_true": torch.tensor(labels).view(-1, 1),


# Ignore, just testing

In [8]:
import numpy as np

In [9]:
LM_pred_path = './prt_lm/cora/microsoft/deberta-base-raw-text.pred'
preds = np.array(
                np.memmap(LM_pred_path, mode='r',
                          dtype=np.float16,
                          shape=(2708, 7)))

In [11]:
np.argmax(preds, -1)

array([2, 5, 4, ..., 1, 0, 2], dtype=int64)

In [12]:
trainer.data

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
│                                                                                                  │
│ ❱ 1 trainer.data                                                                                 │
│   2                                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
NameError: name 'trainer' is not defined

In [13]:
t_test = LMTrainer(cfg)

preproc
tokenizer
<class 'torch.utils.data.dataset.Subset'>


Some weights of the model checkpoint at microsoft/deberta-base were not used when initializing DebertaModel: ['lm_predictions.lm_head.dense.bias', 'lm_predictions.lm_head.bias', 'lm_predictions.lm_head.LayerNorm.weight', 'lm_predictions.lm_head.LayerNorm.bias', 'lm_predictions.lm_head.dense.weight']
- This IS expected if you are initializing DebertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DebertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).



Number of parameters: 138607111


In [17]:
t_test.data.y

tensor([2, 5, 4,  ..., 1, 0, 2])

In [18]:
import torch
import itertools
from torch_geometric.datasets import Planetoid, Actor
from torch_geometric.transforms import NormalizeFeatures
from tqdm import tqdm

In [20]:
cora = Planetoid(root='data/Planetoid', name='Cora', transform=NormalizeFeatures())

In [21]:
cora[0].y

tensor([3, 4, 4,  ..., 3, 3, 3])

In [24]:
dataset = Planetoid('dataset', 'cora',
                        transform=NormalizeFeatures())

In [25]:
dataset[0].y

tensor([3, 4, 4,  ..., 3, 3, 3])

In [26]:
t_test.data

Data(x=[2708, 1433], edge_index=[2, 10556], y=[2708], train_mask=[2708], val_mask=[2708], test_mask=[2708], num_nodes=2708, train_id=[1624], val_id=[542], test_id=[542])

In [31]:
np.unique(dataset[0].y.numpy(),return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6], dtype=int64),
 array([351, 217, 418, 818, 426, 298, 180], dtype=int64))

In [32]:
np.unique(t_test.data.y.numpy(),return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6], dtype=int64),
 array([298, 418, 818, 426, 217, 180, 351], dtype=int64))

In [42]:
import json

In [40]:
def load_cora_tape():
    text = []
    #files = os.listdir('./data/Cora_TAPE')
    #return files
    for i in range(2708):
        with open('./data/Cora_TAPE/'+str(i)+'.json') as f:
            data = json.load(f)
            text.append(data['choices'][0]['message']['content'])
        f.close()
    return text

In [43]:
text = load_cora_tape()

In [39]:
'0.json' in files

True